/// Emoji shortcode mappings for Discord/Slack-style emoji picker
/// Format: (shortcode, emoji, description)

pub const EMOJIS: &[(&str, &str, &str)] = &[
    // Smileys & Emotion
    ("smile", "😄", "smiling face with open mouth"),
    ("smiley", "😃", "smiling face with big eyes"),
    ("grin", "😀", "grinning face"),
    ("grinning", "😀", "grinning face"),
    ("joy", "😂", "face with tears of joy"),
    ("rofl", "🤣", "rolling on floor laughing"),
    ("laughing", "😆", "grinning squinting face"),
    ("sweat_smile", "😅", "grinning face with sweat"),
    ("innocent", "😇", "smiling face with halo"),
    ("wink", "😉", "winking face"),
    ("blush", "😊", "smiling face with smiling eyes"),
    ("relaxed", "☺️", "smiling face"),
    ("yum", "😋", "face savoring food"),
    ("relieved", "😌", "relieved face"),
    ("heart_eyes", "😍", "smiling face with heart-eyes"),
    ("kissing_heart", "😘", "face blowing a kiss"),
    ("kissing", "😗", "kissing face"),
    ("stuck_out_tongue", "😛", "face with tongue"),
    ("stuck_out_tongue_winking_eye", "😜", "winking face with tongue"),
    ("crazy_face", "🤪", "zany face"),
    ("thinking", "🤔", "thinking face"),
    ("think", "🤔", "thinking face"),
    ("raised_eyebrow", "🤨", "face with raised eyebrow"),
    ("neutral_face", "😐", "neutral face"),
    ("expressionless", "😑", "expressionless face"),
    ("no_mouth", "😶", "face without mouth"),
    ("smirk", "😏", "smirking face"),
    ("unamused", "😒", "unamused face"),
    ("roll_eyes", "🙄", "face with rolling eyes"),
    ("grimacing", "😬", "grimacing face"),
    ("lying_face", "🤥", "lying face"),
    ("shushing_face", "🤫", "shushing face"),
    ("zipper_mouth", "🤐", "zipper-mouth face"),
    ("money_mouth", "🤑", "money-mouth face"),
    ("nerd", "🤓", "nerd face"),
    ("sunglasses", "😎", "smiling face with sunglasses"),
    ("cool", "😎", "smiling face with sunglasses"),
    ("clown", "🤡", "clown face"),
    ("cowboy", "🤠", "cowboy hat face"),
    ("partying_face", "🥳", "partying face"),
    ("party", "🥳", "partying face"),
    ("disguised_face", "🥸", "disguised face"),
    ("pleading_face", "🥺", "pleading face"),
    ("pleading", "🥺", "pleading face"),
    ("sad", "😢", "crying face"),
    ("cry", "😢", "crying face"),
    ("sob", "😭", "loudly crying face"),
    ("angry", "😠", "angry face"),
    ("rage", "😡", "pouting face"),
    ("exploding_head", "🤯", "exploding head"),
    ("flushed", "😳", "flushed face"),
    ("hot_face", "🥵", "hot face"),
    ("cold_face", "🥶", "cold face"),
    ("scream", "😱", "face screaming in fear"),
    ("fearful", "😨", "fearful face"),
    ("cold_sweat", "😰", "anxious face with sweat"),
    ("disappointed", "😞", "disappointed face"),
    ("worried", "😟", "worried face"),
    ("confused", "😕", "confused face"),
    ("upside_down", "🙃", "upside-down face"),
    ("skull", "💀", "skull"),
    ("ghost", "👻", "ghost"),
    ("alien", "👽", "alien"),
    ("robot", "🤖", "robot"),
    ("poop", "💩", "pile of poo"),
    ("fire", "🔥", "fire"),
    ("100", "💯", "hundred points"),
    ("sparkles", "✨", "sparkles"),
    ("star", "⭐", "star"),
    ("stars", "🌟", "glowing star"),
    ("zap", "⚡", "high voltage"),
    ("boom", "💥", "collision"),
    ("collision", "💥", "collision"),
    
    // Gestures & Body
    ("thumbsup", "👍", "thumbs up"),
    ("+1", "👍", "thumbs up"),
    ("thumbsdown", "👎", "thumbs down"),
    ("-1", "👎", "thumbs down"),
    ("ok_hand", "👌", "OK hand"),
    ("ok", "👌", "OK hand"),
    ("punch", "👊", "oncoming fist"),
    ("fist", "✊", "raised fist"),
    ("wave", "👋", "waving hand"),
    ("clap", "👏", "clapping hands"),
    ("raised_hands", "🙌", "raising hands"),
    ("pray", "🙏", "folded hands"),
    ("handshake", "🤝", "handshake"),
    ("muscle", "💪", "flexed biceps"),
    ("point_up", "☝️", "index pointing up"),
    ("point_down", "👇", "backhand index pointing down"),
    ("point_left", "👈", "backhand index pointing left"),
    ("point_right", "👉", "backhand index pointing right"),
    ("middle_finger", "🖕", "middle finger"),
    ("v", "✌️", "victory hand"),
    ("peace", "✌️", "victory hand"),
    ("metal", "🤘", "sign of the horns"),
    ("call_me", "🤙", "call me hand"),
    ("fingers_crossed", "🤞", "crossed fingers"),
    ("pinching_hand", "🤏", "pinching hand"),
    ("eyes", "👀", "eyes"),
    ("eye", "👁️", "eye"),
    ("brain", "🧠", "brain"),
    
    // Hearts & Love
    ("heart", "❤️", "red heart"),
    ("red_heart", "❤️", "red heart"),
    ("love", "❤️", "red heart"),
    ("orange_heart", "🧡", "orange heart"),
    ("yellow_heart", "💛", "yellow heart"),
    ("green_heart", "💚", "green heart"),
    ("blue_heart", "💙", "blue heart"),
    ("purple_heart", "💜", "purple heart"),
    ("black_heart", "🖤", "black heart"),
    ("white_heart", "🤍", "white heart"),
    ("broken_heart", "💔", "broken heart"),
    ("heartbeat", "💓", "beating heart"),
    ("heartpulse", "💗", "growing heart"),
    ("sparkling_heart", "💖", "sparkling heart"),
    ("cupid", "💘", "heart with arrow"),
    ("gift_heart", "💝", "heart with ribbon"),
    ("revolving_hearts", "💞", "revolving hearts"),
    ("two_hearts", "💕", "two hearts"),
    ("kiss", "💋", "kiss mark"),
    
    // Animals
    ("dog", "🐕", "dog"),
    ("cat", "🐈", "cat"),
    ("mouse", "🐁", "mouse"),
    ("rabbit", "🐇", "rabbit"),
    ("fox", "🦊", "fox"),
    ("bear", "🐻", "bear"),
    ("panda", "🐼", "panda"),
    ("koala", "🐨", "koala"),
    ("tiger", "🐯", "tiger face"),
    ("lion", "🦁", "lion"),
    ("cow", "🐄", "cow"),
    ("pig", "🐷", "pig face"),
    ("frog", "🐸", "frog"),
    ("monkey", "🐵", "monkey face"),
    ("chicken", "🐔", "chicken"),
    ("penguin", "🐧", "penguin"),
    ("bird", "🐦", "bird"),
    ("eagle", "🦅", "eagle"),
    ("owl", "🦉", "owl"),
    ("bat", "🦇", "bat"),
    ("wolf", "🐺", "wolf"),
    ("unicorn", "🦄", "unicorn"),
    ("bee", "🐝", "honeybee"),
    ("bug", "🐛", "bug"),
    ("butterfly", "🦋", "butterfly"),
    ("snail", "🐌", "snail"),
    ("snake", "🐍", "snake"),
    ("turtle", "🐢", "turtle"),
    ("octopus", "🐙", "octopus"),
    ("crab", "🦀", "crab"),
    ("fish", "🐟", "fish"),
    ("shark", "🦈", "shark"),
    ("whale", "🐋", "whale"),
    ("dolphin", "🐬", "dolphin"),
    
    // Food & Drink
    ("apple", "🍎", "red apple"),
    ("banana", "🍌", "banana"),
    ("orange", "🍊", "tangerine"),
    ("lemon", "🍋", "lemon"),
    ("watermelon", "🍉", "watermelon"),
    ("grapes", "🍇", "grapes"),
    ("strawberry", "🍓", "strawberry"),
    ("peach", "🍑", "peach"),
    ("cherry", "🍒", "cherries"),
    ("pizza", "🍕", "pizza"),
    ("burger", "🍔", "hamburger"),
    ("fries", "🍟", "french fries"),
    ("hotdog", "🌭", "hot dog"),
    ("taco", "🌮", "taco"),
    ("burrito", "🌯", "burrito"),
    ("sushi", "🍣", "sushi"),
    ("ramen", "🍜", "steaming bowl"),
    ("egg", "🥚", "egg"),
    ("bacon", "🥓", "bacon"),
    ("bread", "🍞", "bread"),
    ("cake", "🎂", "birthday cake"),
    ("cookie", "🍪", "cookie"),
    ("chocolate", "🍫", "chocolate bar"),
    ("candy", "🍬", "candy"),
    ("icecream", "🍦", "soft ice cream"),
    ("donut", "🍩", "doughnut"),
    ("coffee", "☕", "hot beverage"),
    ("tea", "🍵", "teacup"),
    ("beer", "🍺", "beer mug"),
    ("beers", "🍻", "clinking beer mugs"),
    ("wine", "🍷", "wine glass"),
    ("cocktail", "🍸", "cocktail glass"),
    ("champagne", "🍾", "bottle with popping cork"),
    
    // Activities & Sports
    ("soccer", "⚽", "soccer ball"),
    ("basketball", "🏀", "basketball"),
    ("football", "🏈", "american football"),
    ("baseball", "⚾", "baseball"),
    ("tennis", "🎾", "tennis"),
    ("volleyball", "🏐", "volleyball"),
    ("golf", "⛳", "flag in hole"),
    ("trophy", "🏆", "trophy"),
    ("medal", "🏅", "sports medal"),
    ("video_game", "🎮", "video game"),
    ("game", "🎮", "video game"),
    ("controller", "🎮", "video game"),
    ("dice", "🎲", "game die"),
    ("chess", "♟️", "chess pawn"),
    ("dart", "🎯", "direct hit"),
    ("bowling", "🎳", "bowling"),
    
    // Objects & Tech
    ("computer", "💻", "laptop"),
    ("laptop", "💻", "laptop"),
    ("desktop", "🖥️", "desktop computer"),
    ("keyboard", "⌨️", "keyboard"),
    ("phone", "📱", "mobile phone"),
    ("mobile", "📱", "mobile phone"),
    ("tablet", "📱", "mobile phone"),
    ("camera", "📷", "camera"),
    ("tv", "📺", "television"),
    ("radio", "📻", "radio"),
    ("headphones", "🎧", "headphone"),
    ("microphone", "🎤", "microphone"),
    ("speaker", "🔊", "speaker high volume"),
    ("mute", "🔇", "muted speaker"),
    ("bell", "🔔", "bell"),
    ("no_bell", "🔕", "bell with slash"),
    ("bulb", "💡", "light bulb"),
    ("flashlight", "🔦", "flashlight"),
    ("battery", "🔋", "battery"),
    ("plug", "🔌", "electric plug"),
    ("gear", "⚙️", "gear"),
    ("wrench", "🔧", "wrench"),
    ("hammer", "🔨", "hammer"),
    ("tools", "🛠️", "hammer and wrench"),
    ("lock", "🔒", "locked"),
    ("unlock", "🔓", "unlocked"),
    ("key", "🔑", "key"),
    ("shield", "🛡️", "shield"),
    ("link", "🔗", "link"),
    ("paperclip", "📎", "paperclip"),
    ("scissors", "✂️", "scissors"),
    ("pencil", "✏️", "pencil"),
    ("pen", "🖊️", "pen"),
    ("book", "📖", "open book"),
    ("books", "📚", "books"),
    ("memo", "📝", "memo"),
    ("clipboard", "📋", "clipboard"),
    ("calendar", "📅", "calendar"),
    ("chart", "📊", "bar chart"),
    ("folder", "📁", "file folder"),
    ("inbox", "📥", "inbox tray"),
    ("outbox", "📤", "outbox tray"),
    ("email", "📧", "e-mail"),
    ("envelope", "✉️", "envelope"),
    ("package", "📦", "package"),
    ("mailbox", "📬", "open mailbox with raised flag"),
    
    // Symbols
    ("check", "✅", "check mark button"),
    ("checkmark", "✔️", "check mark"),
    ("x", "❌", "cross mark"),
    ("cross", "❌", "cross mark"),
    ("question", "❓", "question mark"),
    ("exclamation", "❗", "exclamation mark"),
    ("warning", "⚠️", "warning"),
    ("no_entry", "⛔", "no entry"),
    ("prohibited", "🚫", "prohibited"),
    ("stop", "🛑", "stop sign"),
    ("recycle", "♻️", "recycling symbol"),
    ("infinity", "♾️", "infinity"),
    ("zzz", "💤", "zzz"),
    ("speech_balloon", "💬", "speech balloon"),
    ("thought_balloon", "💭", "thought balloon"),
    ("wave_dash", "〰️", "wavy dash"),
    ("arrow_up", "⬆️", "up arrow"),
    ("arrow_down", "⬇️", "down arrow"),
    ("arrow_left", "⬅️", "left arrow"),
    ("arrow_right", "➡️", "right arrow"),
    ("refresh", "🔄", "counterclockwise arrows"),
    ("back", "🔙", "back arrow"),
    ("soon", "🔜", "soon arrow"),
    ("top", "🔝", "top arrow"),
    ("new", "🆕", "new button"),
    ("free", "🆓", "free button"),
    ("up", "🆙", "up button"),
    ("cool_symbol", "🆒", "cool button"),
    ("ok_button", "🆗", "OK button"),
    ("sos", "🆘", "SOS button"),
    ("info", "ℹ️", "information"),
    ("abc", "🔤", "input latin letters"),
    ("atm", "🏧", "ATM sign"),
    ("parking", "🅿️", "P button"),
    
    // Misc
    ("rocket", "🚀", "rocket"),
    ("airplane", "✈️", "airplane"),
    ("car", "🚗", "automobile"),
    ("bus", "🚌", "bus"),
    ("train", "🚂", "locomotive"),
    ("ship", "🚢", "ship"),
    ("house", "🏠", "house"),
    ("office", "🏢", "office building"),
    ("hospital", "🏥", "hospital"),
    ("school", "🏫", "school"),
    ("church", "⛪", "church"),
    ("tent", "⛺", "tent"),
    ("mountain", "⛰️", "mountain"),
    ("volcano", "🌋", "volcano"),
    ("beach", "🏖️", "beach with umbrella"),
    ("island", "🏝️", "desert island"),
    ("sun", "☀️", "sun"),
    ("moon", "🌙", "crescent moon"),
    ("cloud", "☁️", "cloud"),
    ("rain", "🌧️", "cloud with rain"),
    ("snow", "❄️", "snowflake"),
    ("thunder", "⛈️", "cloud with lightning and rain"),
    ("rainbow", "🌈", "rainbow"),
    ("umbrella", "☂️", "umbrella"),
    ("hourglass", "⏳", "hourglass not done"),
    ("watch", "⌚", "watch"),
    ("clock", "🕐", "one o'clock"),
    ("alarm", "⏰", "alarm clock"),
    ("timer", "⏱️", "stopwatch"),
    ("gift", "🎁", "wrapped gift"),
    ("balloon", "🎈", "balloon"),
    ("tada", "🎉", "party popper"),
    ("confetti", "🎊", "confetti ball"),
    ("ribbon", "🎀", "ribbon"),
    ("crown", "👑", "crown"),
    ("ring", "💍", "ring"),
    ("gem", "💎", "gem stone"),
    ("lipstick", "💄", "lipstick"),
    ("dress", "👗", "dress"),
    ("shirt", "👕", "t-shirt"),
    ("jeans", "👖", "jeans"),
    ("shoe", "👟", "running shoe"),
    ("boot", "👢", "woman's boot"),
    ("hat", "🎩", "top hat"),
    ("glasses", "👓", "glasses"),
    
    // Flags
    ("flag_us", "🇺🇸", "flag: United States"),
    ("flag_uk", "🇬🇧", "flag: United Kingdom"),
    ("flag_de", "🇩🇪", "flag: Germany"),
    ("flag_fr", "🇫🇷", "flag: France"),
    ("flag_jp", "🇯🇵", "flag: Japan"),
    ("flag_kr", "🇰🇷", "flag: South Korea"),
    ("flag_cn", "🇨🇳", "flag: China"),
    ("flag_in", "🇮🇳", "flag: India"),
    ("flag_br", "🇧🇷", "flag: Brazil"),
    ("flag_ca", "🇨🇦", "flag: Canada"),
    ("flag_au", "🇦🇺", "flag: Australia"),
    ("flag_ru", "🇷🇺", "flag: Russia"),
    ("checkered_flag", "🏁", "chequered flag"),
    ("white_flag", "🏳️", "white flag"),
    ("black_flag", "🏴", "black flag"),
    ("pirate_flag", "🏴‍☠️", "pirate flag"),
    ("rainbow_flag", "🏳️‍🌈", "rainbow flag"),
];

/// Find emojis matching a partial shortcode
pub fn find_matching_emojis(partial: &str) -> Vec<(&'static str, &'static str, &'static str)> {
    let partial_lower = partial.to_lowercase();
    EMOJIS
        .iter()
        .filter(|(shortcode, _, _)| shortcode.starts_with(&partial_lower))
        .copied()
        .take(10) // Limit to 10 suggestions
        .collect()
}

/// Get emoji by exact shortcode
pub fn get_emoji(shortcode: &str) -> Option<&'static str> {
    let shortcode_lower = shortcode.to_lowercase();
    EMOJIS
        .iter()
        .find(|(sc, _, _)| *sc == shortcode_lower)
        .map(|(_, emoji, _)| *emoji)
}
